# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions
name: Node.js CI

on:
    push:
        branches: [master]
    pull_request:
        branches: [master]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: Use Node.js 24
              uses: actions/setup-node@v4
              with:
                  node-version: '24'
                  check-latest: true
                  cache: 'npm' # speeds up npm ci based on package-lock.json

            - name: Show versions
              run: node -v && npm -v

            - name: Install deps (npm 10 syntax)
              run: npm ci --include=dev

            - name: Build
              run: npm run build --if-present

            - name: Test
              run: npm test
              env:
                  CI: true
